### ISSUE TITLE
Fix InstallPackages.R File, Vet on Blank Area has all required

### ISSUE THREAD

**Issue by cfelletter** [usbr/MTOM#58]

**Comment by rabutler-usbr** [comment]
It seems like using packrat, might be a good solution (https://rstudio.github.io/packrat/)

**Comment by cfelletter** [comment]
Branch fix_r_code addresses this issue. Thanks @rabutler-usbr. Should I make a R project for my generic script? I don't have much experience using projects but know they have benefits 

Alan:
I've taken a crack at setting up the MTOM repository to use packrat. These changes have been made to the fix_r_code branch of the repo. There's also a quick wiki available at https://github.com/usbr/MTOM/wiki/Using-R-for-post-processing-MTOM-results

One of the main changes is that it relies on the RStudio project file, which I've placed in the main top-level directory. So that becomes the working directory in R, and it's best not to change the working directory manually, unless entirely necessary. 

So, I also updated the MTOM_Compare_5Yr_RWDataPlyr.R file to work with this working directory.

You/and others, should be able to follow the instructions on the wiki, and then source("Output Data/RDF Process/MTOM_Compare_5Yr_RWDataPlyr.R") and have the figures created without doing anything else. 

packrat should make installing all the necessary packages much easier, and will ensure that whatever versions of the packages we are using- others are using too. We can talk about how to update packages if we decide to go this way. 

Test it out, and let me know what you think. We can move the Rproject to a sub-directory if that makes more sense.

Finally, in all my testing today, installing RWDataPlyr from github takes a bit of time, and it won't include the vignette by default. So, I'm in the process of submitting to CRAN. With any luck it will be up by Monday, and that should simplify everyone's life.

**Comment by rabutler-usbr** [comment]
No problem, @cfelletter. Once you've tested it out we can pull into the dev branch. It shouldn't conflict with any of the other ongoing development tasks. 

I'd say we want 1 Rstudio project for all of MTOM, which is why I put it at the top-level. I could also see some benefits to keeping it in the output processing folder, but then it would make it a little awkward for accessing @sbaker2423 adjustDates.R file. 

As to whether or not you created an entire different project (and new repository)- that could also make sense. That's what we did with CRSS, i.e., Process-CRSS-Res is not stored in the CRSS_DIR. One benefit is that if we are sharing code between CRSS and MTOM, it would be better to have it in a folder that is not unique to either model directory. It would also keep the model directories a little cleaner. 

Maybe we can keep it in MTOM_DIR for now, and see if it relies on any of the Process-CRSS-Res code- if it does then that might be a good enough reason to move it into a new location. Or add that generic code to the CRSSIO package.

**Comment by cfelletter** [comment]
@rabutler-usbr got an error when doing source("Output Data/RDF Process/MTOM_Compare_5Yr_RWDataPlyr.R")

Error in mutate_impl(.data, dots) : 
  Evaluation error: there is no package called <U+0091>zoo<U+0092>.

Its getting triggered by rw_scen_aggregate() which is first called to create '_pe_' 

Let me know Monday how I can help you debug this.

**Comment by rabutler-usbr** [comment]
Just be sure to close and restart RStudio after all the packages install.

**Comment by cfelletter** [comment]
This has been replaced by https://github.com/usbr/Process-MTOM-R
